project.name=webLab3
project.version=1.0
project.encoding=UTF-8
java.source.version=17
java.target.version=17

src.dir=src/main/java
resources.dir=src/main/resources
webapp.dir=src/main/webapp
test.src.dir=src/test/java
build.dir=build
classes.dir=${build.dir}/classes
test.classes.dir=${build.dir}/test-classes
javadoc.dir=${build.dir}/javadoc
checksums.dir=${build.dir}/checksums
native2ascii.out.dir=${build.dir}/native2ascii
alt.work.dir=${build.dir}/alt-src
alt.build.dir=${build.dir}/alt-build
alt.dist.dir=${dist.dir}/alt
team.work.dir=${build.dir}/team
team.dist.dir=${dist.dir}/team
reports.dir=reports/junit
dist.dir=dist
lib.dir=target/ant-lib

jar.file=${dist.dir}/${project.name}.jar
alt.jar.file=${alt.dist.dir}/${project.name}-alt.jar
team.zip.file=${team.dist.dir}/${project.name}-team.zip

manifest.version.attribute=Implementation-Version
manifest.main.attribute=Main-Class
manifest.created.by.attribute=Created-By
manifest.md5.attribute=Project-Files-MD5
manifest.sha1.attribute=Project-Files-SHA1
manifest.created.by=Apache Ant
main.class=by.rozze.weblab3.Main

maven.command=./mvnw
maven.copy.dependencies.args=-q dependency:copy-dependencies -DincludeScope=test -DoutputDirectory=target/ant-lib
maven.copy.junit.console.args=-q dependency:copy -Dartifact=org.junit.platform:junit-platform-console-standalone:${junit.platform.console.version} -DoutputDirectory=target/ant-lib
junit.platform.console.version=1.11.0
junit.console.jar=${lib.dir}/junit-platform-console-standalone-${junit.platform.console.version}.jar

xml.validate.lenient=true

localization.src.dir=src/main/resources/i18n
localization.include.pattern=**/*.properties
native2ascii.encoding=UTF-8

music.player=afplay
music.file=music/success.aiff
music.fallback.message=Build completed successfully.

env.java.executable=java
env.jvm.args=-Xmx512m -Dfile.encoding=UTF-8
env.program.args=--from-ant-env

svn.url=file:///Users/rozze/svn-labs/webLab3repo/trunk
svn.export.quiet.flag=-q

git.report.message=add junit xml report

alt.class.package.dir=by/rozze/weblab3/Service
alt.class.old=AreaCheckService
alt.class.new=AreaCheckAltService
alt.var.old=radius
alt.var.new=areaRadius
alt.var2.old=result
alt.var2.new=areaResult

war.file=${dist.dir}/${project.name}.war

deploy.host=helios.cs.ifmo.ru
deploy.port=2222
deploy.user=s471800

deploy.remote.war=/home/studs/s471800/webLab3.war

wildfly.remote.cli=/home/studs/s471800/wildfly-38.0.0.Beta1/bin/jboss-cli.sh
wildfly.remote.controller=localhost:47180
wildfly.cli.java.opts=-Xms64m -Xmx256m -XX:MaxMetaspaceSize=256m
wildfly.management.user=user
wildfly.management.password=XXXXXXXX

deploy.name=webLab3.war
deploy.runtime.name=webLab3.war

deploy.url=http://localhost:4718/webLab3/main.xhtml